export type PlanId = 'free' | 'premium' | 'family' | 'professional' | 'business' | 'enterprise';

export type FeatureAccessValue = true | false | 'partial';

export type SecurityModuleId =
  | 'malware'
  | 'ransomware'
  | 'phishing'
  | 'browser'
  | 'email'
  | 'dark-web'
  | 'identity'
  | 'biometrics'
  | 'social'
  | 'family-safety'
  | 'website-protection'
  | 'personal-firewall'
  | 'scam'
  | 'fraud'
  | 'account-takeover'
  | 'credential-leaks'
  | 'network'
  | 'wifi'
  | 'vpn'
  | 'vulnerability'
  | 'device'
  | 'camera-mic'
  | 'privacy'
  | 'file'
  | 'zero-day'
  | 'ai-attacks'
  | 'deepfake'
  | 'threat-intel'
  | 'ddos-monitoring'
  | 'sql-injection'
  | 'api-security'
  | 'siem'
  | 'compliance'
  | 'executive-reporting';

export type ModuleCategory = 'Core Defense' | 'Identity & Social' | 'Family & Web' | 'Network' | 'Privacy' | 'AI Intelligence';

export type SecurityStatus = 'Protected' | 'Monitoring' | 'Warning' | 'Locked';

export interface PlanDefinition {
  id: PlanId;
  name: string;
  tagline: string;
  monthly: number | null;
  yearly: number | null;
  devices: string;
  users: string;
  color: string;
  popular?: boolean;
  enterprise?: boolean;
  features: Record<string, FeatureAccessValue>;
}

export interface SecurityModule {
  id: SecurityModuleId;
  title: string;
  shortTitle: string;
  category: ModuleCategory;
  description: string;
  color: string;
  accent: string;
  score: number;
  incidents: number;
  status: SecurityStatus;
  minPlan: PlanId;
  metrics: { label: string; value: string; trend: string }[];
  checks: { label: string; detail: string; status: SecurityStatus }[];
  signals: string[];
  recommendations: string[];
}

export interface SecurityReport {
  id: string;
  title: string;
  detail: string;
  category: 'Operations' | 'Implementation' | 'Research';
  status: 'Ready' | 'Actionable' | 'Monitoring';
  kpis: string[];
  actions: string[];
}

export const PLAN_RANK: Record<PlanId, number> = {
  free: 0,
  premium: 1,
  family: 2,
  professional: 3,
  business: 4,
  enterprise: 5,
};

export const PLANS: PlanDefinition[] = [
  {
    id: 'free',
    name: 'Free',
    tagline: 'Essential personal monitoring',
    monthly: 0,
    yearly: 0,
    devices: '1 device',
    users: '1 user',
    color: '#6b7280',
    features: {
      'Security score': true,
      'Basic malware scan': true,
      'AI assistant': 'partial',
      'Vulnerability checks': 'partial',
      'Real-time protection': false,
      'Dark web monitoring': false,
      'Social media protection': false,
      'Family controls': false,
      'Child & family safety': false,
      'Website protection': false,
      'Personal firewall': 'partial',
      'Team console': false,
      'Enterprise integrations': false,
    },
  },
  {
    id: 'premium',
    name: 'Premium',
    tagline: 'Complete personal shield',
    monthly: 9.99,
    yearly: 95.88,
    devices: '5 devices',
    users: '1 user',
    color: '#00d4ff',
    popular: true,
    features: {
      'Security score': true,
      'Basic malware scan': true,
      'AI assistant': true,
      'Vulnerability checks': true,
      'Real-time protection': true,
      'Dark web monitoring': true,
      'Social media protection': 'partial',
      'Family controls': false,
      'Child & family safety': false,
      'Website protection': 'partial',
      'Personal firewall': true,
      'Team console': false,
      'Enterprise integrations': false,
    },
  },
  {
    id: 'family',
    name: 'Family',
    tagline: 'Protect everyone at home',
    monthly: 19.99,
    yearly: 191.88,
    devices: '15 devices',
    users: '6 users',
    color: '#0ff4c6',
    features: {
      'Security score': true,
      'Basic malware scan': true,
      'AI assistant': true,
      'Vulnerability checks': true,
      'Real-time protection': true,
      'Dark web monitoring': true,
      'Social media protection': true,
      'Family controls': true,
      'Child & family safety': true,
      'Website protection': 'partial',
      'Personal firewall': true,
      'Team console': false,
      'Enterprise integrations': false,
    },
  },
  {
    id: 'professional',
    name: 'Professional',
    tagline: 'Power-user and creator defense',
    monthly: 34.99,
    yearly: 335.88,
    devices: '25 devices',
    users: '3 users',
    color: '#7c3aed',
    features: {
      'Security score': true,
      'Basic malware scan': true,
      'AI assistant': true,
      'Vulnerability checks': true,
      'Real-time protection': true,
      'Dark web monitoring': true,
      'Social media protection': true,
      'Family controls': true,
      'Child & family safety': true,
      'Website protection': true,
      'Personal firewall': true,
      'Team console': 'partial',
      'Enterprise integrations': false,
    },
  },
  {
    id: 'business',
    name: 'Business',
    tagline: 'Team-wide cyber defense',
    monthly: 99.99,
    yearly: 959.88,
    devices: '250 devices',
    users: '50 seats',
    color: '#f59e0b',
    features: {
      'Security score': true,
      'Basic malware scan': true,
      'AI assistant': true,
      'Vulnerability checks': true,
      'Real-time protection': true,
      'Dark web monitoring': true,
      'Social media protection': true,
      'Family controls': true,
      'Child & family safety': true,
      'Website protection': true,
      'Personal firewall': true,
      'Team console': true,
      'Enterprise integrations': 'partial',
    },
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    tagline: 'Unlimited managed security',
    monthly: null,
    yearly: null,
    devices: 'Unlimited',
    users: 'Unlimited',
    color: '#ff3b5c',
    enterprise: true,
    features: {
      'Security score': true,
      'Basic malware scan': true,
      'AI assistant': true,
      'Vulnerability checks': true,
      'Real-time protection': true,
      'Dark web monitoring': true,
      'Social media protection': true,
      'Family controls': true,
      'Child & family safety': true,
      'Website protection': true,
      'Personal firewall': true,
      'Team console': true,
      'Enterprise integrations': true,
    },
  },
];

export const FEATURE_ACCESS: Record<string, { minPlan: PlanId }> = {
  'malware-protection': { minPlan: 'free' },
  'security-score': { minPlan: 'free' },
  'basic-vulnerability': { minPlan: 'free' },
  'ai-assistant': { minPlan: 'premium' },
  'real-time-protection': { minPlan: 'premium' },
  'phishing-detection': { minPlan: 'premium' },
  'ransomware-protection': { minPlan: 'premium' },
  'browser-protection': { minPlan: 'premium' },
  'email-protection': { minPlan: 'premium' },
  'dark-web-monitoring': { minPlan: 'premium' },
  'identity-protection': { minPlan: 'family' },
  'social-media-protection': { minPlan: 'family' },
  'social-profile-analysis': { minPlan: 'family' },
  'child-family-safety': { minPlan: 'family' },
  'website-protection': { minPlan: 'premium' },
  'personal-security-firewall': { minPlan: 'premium' },
  'scam-detection': { minPlan: 'family' },
  'fraud-detection': { minPlan: 'professional' },
  'account-takeover-detection': { minPlan: 'professional' },
  'credential-leak-monitoring': { minPlan: 'premium' },
  'network-security': { minPlan: 'premium' },
  'wifi-security': { minPlan: 'premium' },
  'vpn-support': { minPlan: 'premium' },
  'vulnerability-scanning': { minPlan: 'premium' },
  'device-protection': { minPlan: 'free' },
  'camera-microphone-monitoring': { minPlan: 'professional' },
  'privacy-protection': { minPlan: 'family' },
  'file-protection': { minPlan: 'premium' },
  'zero-day-threat-detection': { minPlan: 'professional' },
  'ai-attack-detection': { minPlan: 'business' },
  'deepfake-detection': { minPlan: 'professional' },
  'real-time-threat-intelligence': { minPlan: 'business' },
  'team-management': { minPlan: 'business' },
  'compliance-tools': { minPlan: 'business' },
  'invoices': { minPlan: 'premium' },
  'ddos-monitoring': { minPlan: 'enterprise' },
  'sql-injection-detection': { minPlan: 'enterprise' },
  'api-security-monitoring': { minPlan: 'enterprise' },
  'siem-integrations': { minPlan: 'enterprise' },
  'executive-reporting': { minPlan: 'enterprise' },
  'enterprise-integrations': { minPlan: 'enterprise' },
};

export const MODULES: SecurityModule[] = [
  {
    id: 'malware',
    title: 'Malware Protection',
    shortTitle: 'Malware',
    category: 'Core Defense',
    description: 'Real-time file, app, and behavior scanning for known and unknown malware.',
    color: '#ff3b5c',
    accent: 'rgba(255,59,92,0.18)',
    score: 96,
    incidents: 2,
    status: 'Protected',
    minPlan: 'free',
    metrics: [
      { label: 'Files watched', value: '18.4K', trend: '+412 today' },
      { label: 'Apps verified', value: '47', trend: 'All signed' },
      { label: 'Blocks', value: '2', trend: 'Last 24h' },
    ],
    checks: [
      { label: 'Real-time scanner', detail: 'Active monitoring of storage, downloads, and app installs.', status: 'Protected' },
      { label: 'Behavior analysis', detail: 'AI anomaly model is watching suspicious process behavior.', status: 'Protected' },
      { label: 'Quarantine vault', detail: '2 files isolated and awaiting review.', status: 'Warning' },
    ],
    signals: ['File hashes', 'App signatures', 'Sandbox behavior', 'Exploit patterns'],
    recommendations: ['Keep automatic scanning enabled.', 'Review quarantined files before restoring them.'],
  },
  {
    id: 'ransomware',
    title: 'Ransomware Protection',
    shortTitle: 'Ransomware',
    category: 'Core Defense',
    description: 'Detects unauthorized encryption, protects critical files, and can isolate risky processes.',
    color: '#7c3aed',
    accent: 'rgba(124,58,237,0.2)',
    score: 93,
    incidents: 0,
    status: 'Protected',
    minPlan: 'premium',
    metrics: [
      { label: 'Critical folders', value: '12', trend: 'Shielded' },
      { label: 'Backups', value: '2.4GB', trend: 'Synced' },
      { label: 'Encryption bursts', value: '0', trend: 'Clean' },
    ],
    checks: [
      { label: 'Encryption monitor', detail: 'No unauthorized high-volume file changes detected.', status: 'Protected' },
      { label: 'Backup shield', detail: 'Critical folders are mirrored to protected storage.', status: 'Protected' },
      { label: 'Network isolation', detail: 'Auto-isolation is ready if ransomware behavior appears.', status: 'Monitoring' },
    ],
    signals: ['File entropy changes', 'Bulk rename events', 'Shadow copy deletion attempts', 'Command-line anomalies'],
    recommendations: ['Enable protected backups for financial documents.', 'Run a weekly ransomware drill.'],
  },
  {
    id: 'phishing',
    title: 'Phishing Detection',
    shortTitle: 'Phishing',
    category: 'Core Defense',
    description: 'Analyzes links, login pages, messages, and emails for spoofing and social engineering.',
    color: '#f59e0b',
    accent: 'rgba(245,158,11,0.18)',
    score: 91,
    incidents: 3,
    status: 'Monitoring',
    minPlan: 'premium',
    metrics: [
      { label: 'Links checked', value: '847', trend: '3 blocked' },
      { label: 'Clone sites', value: '6', trend: 'Detected' },
      { label: 'Inbox risk', value: 'Low', trend: 'Stable' },
    ],
    checks: [
      { label: 'URL reputation', detail: 'Every submitted link is checked against live threat intelligence.', status: 'Protected' },
      { label: 'Visual clone AI', detail: 'Compares suspicious pages against known brand login flows.', status: 'Monitoring' },
      { label: 'Message intent', detail: 'Detects urgency, payment pressure, and credential harvesting cues.', status: 'Protected' },
    ],
    signals: ['Domain age', 'Redirect chains', 'Brand spoofing', 'Urgency language'],
    recommendations: ['Submit any payment or login request before acting.', 'Turn on browser protection for automatic page checks.'],
  },
  {
    id: 'browser',
    title: 'Browser Protection',
    shortTitle: 'Browser',
    category: 'Core Defense',
    description: 'Protects browsing sessions against malicious links, fake login pages, and tracking risks.',
    color: '#00d4ff',
    accent: 'rgba(0,212,255,0.16)',
    score: 89,
    incidents: 4,
    status: 'Protected',
    minPlan: 'premium',
    metrics: [
      { label: 'Tabs protected', value: '31', trend: 'Live' },
      { label: 'Trackers blocked', value: '119', trend: '+22%' },
      { label: 'Risky forms', value: '1', trend: 'Warned' },
    ],
    checks: [
      { label: 'Malicious link shield', detail: 'Blocks access to known phishing and malware endpoints.', status: 'Protected' },
      { label: 'Fake checkout guard', detail: 'Flags lookalike payment pages before card entry.', status: 'Monitoring' },
      { label: 'Session privacy', detail: 'High-risk trackers are being filtered.', status: 'Protected' },
    ],
    signals: ['TLS status', 'Known bad domains', 'Form capture behavior', 'Tracker reputation'],
    recommendations: ['Enable VPN on public Wi-Fi.', 'Use passkeys for banking and admin portals.'],
  },
  {
    id: 'email',
    title: 'Email Protection',
    shortTitle: 'Email',
    category: 'Core Defense',
    description: 'Inspects attachments, sender reputation, content intent, and business email compromise patterns.',
    color: '#0ff4c6',
    accent: 'rgba(15,244,198,0.14)',
    score: 94,
    incidents: 1,
    status: 'Protected',
    minPlan: 'premium',
    metrics: [
      { label: 'Inbox scans', value: '1.2K', trend: '24h' },
      { label: 'Spoofs', value: '1', trend: 'Blocked' },
      { label: 'Attachments', value: '38', trend: 'Clean' },
    ],
    checks: [
      { label: 'Sender reputation', detail: 'Sender domains are checked for age, SPF, DKIM, and DMARC signals.', status: 'Protected' },
      { label: 'Attachment sandbox', detail: 'Risky files are detonated in a simulated environment.', status: 'Protected' },
      { label: 'BEC detection', detail: 'Payment redirection and executive impersonation patterns are watched.', status: 'Monitoring' },
    ],
    signals: ['SPF/DKIM/DMARC', 'Attachment behavior', 'Thread context', 'Financial pressure'],
    recommendations: ['Verify new bank details outside email.', 'Quarantine macro-enabled attachments by default.'],
  },
  {
    id: 'dark-web',
    title: 'Dark Web Monitoring',
    shortTitle: 'Dark Web',
    category: 'Identity & Social',
    description: 'Monitors breach dumps, underground forums, and credential marketplaces for exposed identity data.',
    color: '#7c3aed',
    accent: 'rgba(124,58,237,0.18)',
    score: 82,
    incidents: 1,
    status: 'Warning',
    minPlan: 'premium',
    metrics: [
      { label: 'Identities watched', value: '8', trend: 'Live' },
      { label: 'New leaks', value: '1', trend: 'Needs action' },
      { label: 'Sources', value: '10M+', trend: 'Signals/day' },
    ],
    checks: [
      { label: 'Email breach watch', detail: 'One older email appeared in a newly indexed combo list.', status: 'Warning' },
      { label: 'Password exposure', detail: 'No plaintext password match found in recent collections.', status: 'Protected' },
      { label: 'Card monitor', detail: 'No matching payment cards detected.', status: 'Protected' },
    ],
    signals: ['Credential dumps', 'Forum aliases', 'Paste sites', 'Breach metadata'],
    recommendations: ['Rotate passwords for flagged accounts.', 'Enable MFA everywhere a leak appears.'],
  },
  {
    id: 'identity',
    title: 'Identity Theft Protection',
    shortTitle: 'Identity',
    category: 'Identity & Social',
    description: 'Watches for misuse of identity data, account recovery attempts, and suspicious profile changes.',
    color: '#f59e0b',
    accent: 'rgba(245,158,11,0.16)',
    score: 88,
    incidents: 2,
    status: 'Monitoring',
    minPlan: 'family',
    metrics: [
      { label: 'Identity items', value: '14', trend: 'Monitored' },
      { label: 'Recovery attempts', value: '2', trend: 'Reviewed' },
      { label: 'Fraud risk', value: '18%', trend: 'Low' },
    ],
    checks: [
      { label: 'Account recovery watch', detail: 'Recovery activity is correlated across email, phone, and device signals.', status: 'Monitoring' },
      { label: 'Public profile drift', detail: 'Name, image, and biography changes are reviewed for impersonation.', status: 'Protected' },
      { label: 'Financial identity alerting', detail: 'High-risk identity signals create fraud alerts.', status: 'Monitoring' },
    ],
    signals: ['Recovery events', 'Public profile changes', 'Device metadata', 'Credential reuse'],
    recommendations: ['Add a recovery email you control.', 'Avoid reusing phone numbers on public profiles.'],
  },
  {
    id: 'biometrics',
    title: 'Biometrics & Authentication',
    shortTitle: 'Biometrics',
    category: 'Identity & Social',
    description: 'Configures biometric unlock, passkeys, MFA, recovery controls, trusted-device review, and authentication hardening.',
    color: '#0ff4c6',
    accent: 'rgba(15,244,198,0.16)',
    score: 92,
    incidents: 1,
    status: 'Protected',
    minPlan: 'free',
    metrics: [
      { label: 'Auth methods', value: '3', trend: 'Enabled' },
      { label: 'Trusted devices', value: '4', trend: '1 review' },
      { label: 'MFA coverage', value: '91%', trend: '+6%' },
    ],
    checks: [
      { label: 'Biometric unlock', detail: 'Device biometric authentication is available for secure app access.', status: 'Protected' },
      { label: 'MFA enforcement', detail: 'Plan changes, billing, reports, and protection changes require a second factor.', status: 'Monitoring' },
      { label: 'Trusted-device review', detail: 'One stale device should be removed or reverified.', status: 'Warning' },
    ],
    signals: ['Biometric enrollment', 'Passkey status', 'MFA coverage', 'Trusted devices', 'Recovery codes'],
    recommendations: ['Pair biometrics with a strong device passcode.', 'Enable MFA for account and billing changes.', 'Remove stale trusted devices and rotate recovery codes after device loss.'],
  },
  {
    id: 'social',
    title: 'Social Media Protection Center',
    shortTitle: 'Social Center',
    category: 'Identity & Social',
    description: 'Scans linked accounts, public profiles, business pages, screenshots, links, and conversations for deception and compromise.',
    color: '#00d4ff',
    accent: 'rgba(0,212,255,0.14)',
    score: 87,
    incidents: 5,
    status: 'Monitoring',
    minPlan: 'family',
    metrics: [
      { label: 'Accounts linked', value: '5', trend: 'Scanning' },
      { label: 'Profiles analyzed', value: '84', trend: '+18 week' },
      { label: 'Fraud alerts', value: '7', trend: '2 high' },
    ],
    checks: [
      { label: 'Linked account scanner', detail: 'Reviews public profile drift, suspicious sessions, campaign abuse, and compromise indicators.', status: 'Monitoring' },
      { label: 'Fake profile and page detection', detail: 'Flags impersonation, fake tech support accounts, fraudulent business pages, and cloned creator profiles.', status: 'Protected' },
      { label: 'Scam campaign analysis', detail: 'Scores romance, investment, fake giveaway, phishing, and social engineering patterns from submitted content.', status: 'Protected' },
    ],
    signals: ['Conversation pressure', 'Public metadata', 'Account reputation', 'Profile drift', 'Language inconsistencies', 'Location-related indicators'],
    recommendations: ['Submit suspicious profiles, screenshots, links, or conversations before acting.', 'Use live proof and independent verification before trusting high-risk profiles.', 'Never treat nationality or location as the only reason for a deception decision.'],
  },
  {
    id: 'family-safety',
    title: 'Child & Family Safety',
    shortTitle: 'Family Safety',
    category: 'Family & Web',
    description: 'Helps guardians protect children from grooming, suspicious contacts, fake giveaways, phishing, impersonation, and youth-targeted social engineering.',
    color: '#0ff4c6',
    accent: 'rgba(15,244,198,0.16)',
    score: 86,
    incidents: 4,
    status: 'Monitoring',
    minPlan: 'family',
    metrics: [
      { label: 'Family profiles', value: '4', trend: 'Guarded' },
      { label: 'Contacts reviewed', value: '126', trend: '6 flagged' },
      { label: 'Consent rules', value: '12', trend: 'Active' },
    ],
    checks: [
      { label: 'Guardian consent controls', detail: 'Child protection analysis runs only within configured privacy controls and parental permissions.', status: 'Protected' },
      { label: 'Grooming and coercion detection', detail: 'Looks for secrecy requests, age-inappropriate pressure, isolation, gifts, and migration to unsafe channels.', status: 'Monitoring' },
      { label: 'Youth scam shielding', detail: 'Flags fake giveaways, romance pressure, recruitment fraud, phishing links, and suspicious new contacts.', status: 'Warning' },
    ],
    signals: ['Conversation safety', 'Suspicious contacts', 'Profile age mismatch', 'Link reputation', 'Gift or secrecy pressure', 'Guardian policy'],
    recommendations: ['Review flagged contacts with the child in a supportive way.', 'Keep privacy controls explicit and age appropriate.', 'Block payment, gift card, and off-platform requests from unknown contacts.'],
  },
  {
    id: 'website-protection',
    title: 'Website Protection',
    shortTitle: 'Websites',
    category: 'Family & Web',
    description: 'Registers business websites, stores, portfolios, blogs, and apps, then baselines and monitors security posture continuously.',
    color: '#00d4ff',
    accent: 'rgba(0,212,255,0.16)',
    score: 83,
    incidents: 3,
    status: 'Monitoring',
    minPlan: 'premium',
    metrics: [
      { label: 'Sites monitored', value: '3', trend: '+1 new' },
      { label: 'Baseline health', value: '82%', trend: 'Improving' },
      { label: 'Domain risks', value: '3', trend: 'Review' },
    ],
    checks: [
      { label: 'Security baseline', detail: 'Stores SSL/TLS, DNS, headers, exposed services, public content, and vulnerability posture for each site.', status: 'Monitoring' },
      { label: 'Malicious change monitor', detail: 'Watches for defacement, phishing abuse, suspicious redirects, malware indicators, and reputation drops.', status: 'Warning' },
      { label: 'Credential and domain exposure', detail: 'Correlates exposed credentials, domain age, certificate problems, and brand abuse signals.', status: 'Protected' },
    ],
    signals: ['SSL/TLS status', 'DNS posture', 'Security headers', 'Public content drift', 'Malware indicators', 'Domain reputation'],
    recommendations: ['Register every public site and store a first baseline.', 'Fix missing security headers and weak TLS settings.', 'Schedule website posture scans after deployments.'],
  },
  {
    id: 'personal-firewall',
    title: 'Personal Security Firewall',
    shortTitle: 'Firewall',
    category: 'Core Defense',
    description: 'Intelligent policy engine for suspicious links, risky websites, phishing attempts, scam communications, downloads, network activity, and harmful domains.',
    color: '#ff3b5c',
    accent: 'rgba(255,59,92,0.15)',
    score: 92,
    incidents: 6,
    status: 'Protected',
    minPlan: 'premium',
    metrics: [
      { label: 'Rules active', value: '38', trend: 'Adaptive' },
      { label: 'Filtered today', value: '71', trend: '6 high' },
      { label: 'Auto actions', value: '14', trend: 'Recommended' },
    ],
    checks: [
      { label: 'Link and domain firewall', detail: 'Filters malicious links, harmful domains, suspicious redirects, and phishing pages before interaction.', status: 'Protected' },
      { label: 'Communication risk filter', detail: 'Correlates scam messages, fraudulent downloads, sender reputation, and social engineering intent.', status: 'Monitoring' },
      { label: 'Policy automation', detail: 'Connects user protection settings, entitlements, AI analysis, and notifications to recommend next actions.', status: 'Protected' },
    ],
    signals: ['Domain reputation', 'Download behavior', 'Network anomalies', 'Sender reputation', 'User policy', 'Threat intelligence'],
    recommendations: ['Keep high-risk link warnings enabled.', 'Require confirmation before downloads from unknown domains.', 'Review firewall recommendations after each blocked scam or phishing attempt.'],
  },
  {
    id: 'scam',
    title: 'Scam Detection',
    shortTitle: 'Scams',
    category: 'Identity & Social',
    description: 'Analyzes messages, screenshots, links, phone numbers, and SMS for known scam tactics.',
    color: '#ff3b5c',
    accent: 'rgba(255,59,92,0.14)',
    score: 84,
    incidents: 7,
    status: 'Warning',
    minPlan: 'family',
    metrics: [
      { label: 'SMS checked', value: '96', trend: '4 scam' },
      { label: 'Calls screened', value: '31', trend: '2 spam' },
      { label: 'Profiles risky', value: '3', trend: 'Review' },
    ],
    checks: [
      { label: 'Fake tech support', detail: 'Detects remote access, refund, and urgent support impersonation patterns.', status: 'Monitoring' },
      { label: 'Scam SMS', detail: 'Checks short links, delivery lures, bank lures, and sender reputation.', status: 'Protected' },
      { label: 'Caller reputation', detail: 'Phone numbers are scored using complaint and abuse signals.', status: 'Monitoring' },
    ],
    signals: ['Caller reputation', 'Short links', 'Payment requests', 'Remote access pressure'],
    recommendations: ['Never install remote-control apps from unsolicited calls.', 'Verify delivery and bank messages inside official apps.'],
  },
  {
    id: 'fraud',
    title: 'Fraud Detection',
    shortTitle: 'Fraud',
    category: 'Identity & Social',
    description: 'Scores payment, account, and profile activity to surface fraud and deception risks.',
    color: '#f59e0b',
    accent: 'rgba(245,158,11,0.14)',
    score: 86,
    incidents: 2,
    status: 'Monitoring',
    minPlan: 'professional',
    metrics: [
      { label: 'Fraud score', value: '22%', trend: 'Low' },
      { label: 'Transactions', value: '19', trend: 'Watched' },
      { label: 'Alerts', value: '2', trend: 'Resolved' },
    ],
    checks: [
      { label: 'Payment intent', detail: 'Scans for invoice redirection, refund abuse, and coercive payment cues.', status: 'Protected' },
      { label: 'Behavior baseline', detail: 'Detects unusual timing, device, and account change behavior.', status: 'Monitoring' },
      { label: 'Safety recommendations', detail: 'Generates action steps before payment or account recovery.', status: 'Protected' },
    ],
    signals: ['Behavior changes', 'Payment language', 'Account metadata', 'Device risk'],
    recommendations: ['Use a cooling-off period for unusual payment requests.', 'Require a second approval for large transfers.'],
  },
  {
    id: 'account-takeover',
    title: 'Account Takeover Detection',
    shortTitle: 'ATO',
    category: 'Identity & Social',
    description: 'Detects suspicious login, recovery, MFA, device, and session behavior across protected accounts.',
    color: '#0ff4c6',
    accent: 'rgba(15,244,198,0.14)',
    score: 90,
    incidents: 1,
    status: 'Protected',
    minPlan: 'professional',
    metrics: [
      { label: 'Sessions watched', value: '18', trend: 'Live' },
      { label: 'Risky logins', value: '1', trend: 'Blocked' },
      { label: 'MFA health', value: '92%', trend: '+6%' },
    ],
    checks: [
      { label: 'Login anomaly', detail: 'Detects impossible travel, new devices, and unusual session behavior.', status: 'Protected' },
      { label: 'Recovery guard', detail: 'Flags password reset and MFA reset attempts.', status: 'Monitoring' },
      { label: 'Session revocation', detail: 'Guides users to revoke risky sessions.', status: 'Protected' },
    ],
    signals: ['Session age', 'Device trust', 'Recovery attempts', 'MFA changes'],
    recommendations: ['Use passkeys for high-value accounts.', 'Remove unused trusted devices monthly.'],
  },
  {
    id: 'credential-leaks',
    title: 'Credential Leak Monitoring',
    shortTitle: 'Credentials',
    category: 'Identity & Social',
    description: 'Finds leaked usernames, emails, passwords, API keys, and secrets before attackers use them.',
    color: '#00d4ff',
    accent: 'rgba(0,212,255,0.14)',
    score: 83,
    incidents: 1,
    status: 'Warning',
    minPlan: 'premium',
    metrics: [
      { label: 'Secrets watched', value: '24', trend: 'Active' },
      { label: 'Leaks', value: '1', trend: 'Rotate' },
      { label: 'Coverage', value: '98%', trend: 'Strong' },
    ],
    checks: [
      { label: 'Password breach scan', detail: 'Matches hashed indicators against breach collections.', status: 'Warning' },
      { label: 'API key exposure', detail: 'Developer secrets are checked against public leak sources.', status: 'Protected' },
      { label: 'Reuse warning', detail: 'Flags credentials reused across critical services.', status: 'Monitoring' },
    ],
    signals: ['Breach collections', 'Public repositories', 'Paste data', 'Credential reuse'],
    recommendations: ['Rotate exposed passwords immediately.', 'Move API keys into a secrets manager.'],
  },
  {
    id: 'network',
    title: 'Network Security',
    shortTitle: 'Network',
    category: 'Network',
    description: 'Monitors ports, DNS, firewall posture, risky traffic, and suspicious network activity.',
    color: '#0ff4c6',
    accent: 'rgba(15,244,198,0.14)',
    score: 92,
    incidents: 1,
    status: 'Protected',
    minPlan: 'premium',
    metrics: [
      { label: 'Ports watched', value: '28', trend: 'All safe' },
      { label: 'DNS blocks', value: '11', trend: '24h' },
      { label: 'Risk traffic', value: '1', trend: 'Contained' },
    ],
    checks: [
      { label: 'Firewall posture', detail: 'Unauthorized inbound attempts are blocked.', status: 'Protected' },
      { label: 'Encrypted DNS', detail: 'DNS hijacking protection is active.', status: 'Protected' },
      { label: 'Threat traffic', detail: 'Outbound connections are checked against C2 reputation.', status: 'Monitoring' },
    ],
    signals: ['DNS queries', 'Port exposure', 'C2 reputation', 'Traffic spikes'],
    recommendations: ['Keep encrypted DNS enabled.', 'Review port forwarding on home routers.'],
  },
  {
    id: 'wifi',
    title: 'Wi-Fi Security',
    shortTitle: 'Wi-Fi',
    category: 'Network',
    description: 'Checks network encryption, captive portals, rogue hotspots, and unsafe router settings.',
    color: '#00d4ff',
    accent: 'rgba(0,212,255,0.14)',
    score: 95,
    incidents: 0,
    status: 'Protected',
    minPlan: 'premium',
    metrics: [
      { label: 'Current network', value: 'Trusted', trend: 'WPA3' },
      { label: 'Hotspots blocked', value: '0', trend: 'Today' },
      { label: 'Router risk', value: 'Low', trend: 'Stable' },
    ],
    checks: [
      { label: 'Encryption check', detail: 'Connected network uses modern encryption.', status: 'Protected' },
      { label: 'Rogue hotspot watch', detail: 'SSID impersonation and captive portal risks are monitored.', status: 'Protected' },
      { label: 'Auto VPN prompt', detail: 'VPN is recommended on untrusted networks.', status: 'Monitoring' },
    ],
    signals: ['SSID similarity', 'Encryption type', 'Gateway changes', 'Captive portal behavior'],
    recommendations: ['Avoid banking on open Wi-Fi without VPN.', 'Change default router passwords.'],
  },
  {
    id: 'vpn',
    title: 'VPN Support',
    shortTitle: 'VPN',
    category: 'Network',
    description: 'Guides secure VPN usage with auto-connect recommendations and risky-network alerts.',
    color: '#7c3aed',
    accent: 'rgba(124,58,237,0.16)',
    score: 78,
    incidents: 1,
    status: 'Warning',
    minPlan: 'premium',
    metrics: [
      { label: 'VPN status', value: 'Idle', trend: 'Enable public' },
      { label: 'Unsafe networks', value: '1', trend: 'Last week' },
      { label: 'Private DNS', value: 'On', trend: 'Good' },
    ],
    checks: [
      { label: 'Auto-connect rule', detail: 'VPN auto-connect is currently off.', status: 'Warning' },
      { label: 'Leak check', detail: 'DNS leak checks pass on the current connection.', status: 'Protected' },
      { label: 'Public Wi-Fi alert', detail: 'A prompt appears when joining untrusted networks.', status: 'Monitoring' },
    ],
    signals: ['Network trust', 'DNS leak tests', 'Captive portal', 'Geo-risk context'],
    recommendations: ['Enable VPN auto-connect.', 'Avoid unknown VPN providers with unclear logging policies.'],
  },
  {
    id: 'vulnerability',
    title: 'Vulnerability Scanning',
    shortTitle: 'Vulnerabilities',
    category: 'Core Defense',
    description: 'Scans apps, device posture, network settings, and exposed services for exploitable weakness.',
    color: '#ff3b5c',
    accent: 'rgba(255,59,92,0.14)',
    score: 81,
    incidents: 6,
    status: 'Warning',
    minPlan: 'premium',
    metrics: [
      { label: 'Findings', value: '6', trend: '2 high' },
      { label: 'Patch level', value: '91%', trend: '+4%' },
      { label: 'Last scan', value: '1h', trend: 'Ago' },
    ],
    checks: [
      { label: 'App patch scan', detail: 'Two apps have updates with security fixes.', status: 'Warning' },
      { label: 'Device posture', detail: 'Screen lock, encryption, and OS patch state are healthy.', status: 'Protected' },
      { label: 'Network exposure', detail: 'No unexpected public services found.', status: 'Protected' },
    ],
    signals: ['CVEs', 'Patch versions', 'Configuration posture', 'Service exposure'],
    recommendations: ['Install the two app security updates.', 'Schedule continuous scans overnight.'],
  },
  {
    id: 'device',
    title: 'Device Protection',
    shortTitle: 'Device',
    category: 'Privacy',
    description: 'Checks device health, permissions, storage safety, screen lock, and risky configuration changes.',
    color: '#0ff4c6',
    accent: 'rgba(15,244,198,0.14)',
    score: 97,
    incidents: 0,
    status: 'Protected',
    minPlan: 'free',
    metrics: [
      { label: 'Device health', value: '97', trend: 'Excellent' },
      { label: 'Permissions', value: '21', trend: 'Reviewed' },
      { label: 'Storage risk', value: 'Low', trend: 'Stable' },
    ],
    checks: [
      { label: 'Lock screen', detail: 'Biometric and passcode protection are enabled.', status: 'Protected' },
      { label: 'Risky permissions', detail: 'No newly granted sensitive permissions detected.', status: 'Protected' },
      { label: 'Storage scan', detail: 'Sensitive files are not exposed to risky apps.', status: 'Monitoring' },
    ],
    signals: ['OS posture', 'Permission changes', 'Device encryption', 'App installs'],
    recommendations: ['Keep biometric unlock enabled.', 'Review permissions after installing new apps.'],
  },
  {
    id: 'camera-mic',
    title: 'Camera & Microphone Monitoring',
    shortTitle: 'Camera/Mic',
    category: 'Privacy',
    description: 'Surfaces privacy-sensitive access events and helps revoke risky camera or microphone permissions.',
    color: '#f59e0b',
    accent: 'rgba(245,158,11,0.14)',
    score: 85,
    incidents: 2,
    status: 'Monitoring',
    minPlan: 'professional',
    metrics: [
      { label: 'Access events', value: '12', trend: 'Today' },
      { label: 'Risky apps', value: '2', trend: 'Review' },
      { label: 'Always-on perms', value: '0', trend: 'Good' },
    ],
    checks: [
      { label: 'Mic access watch', detail: 'Recent access events are logged and scored.', status: 'Monitoring' },
      { label: 'Camera permission review', detail: 'Two apps should be changed to ask every time.', status: 'Warning' },
      { label: 'Background access', detail: 'No background camera or microphone usage detected.', status: 'Protected' },
    ],
    signals: ['Permission usage', 'Foreground state', 'App reputation', 'Background access'],
    recommendations: ['Revoke camera access for apps that do not need it.', 'Use temporary permissions when possible.'],
  },
  {
    id: 'privacy',
    title: 'Privacy Protection',
    shortTitle: 'Privacy',
    category: 'Privacy',
    description: 'Reduces tracking, data exposure, location leakage, and risky permission patterns.',
    color: '#00d4ff',
    accent: 'rgba(0,212,255,0.14)',
    score: 89,
    incidents: 3,
    status: 'Monitoring',
    minPlan: 'family',
    metrics: [
      { label: 'Trackers blocked', value: '119', trend: '24h' },
      { label: 'Data brokers', value: '3', trend: 'Opt-out' },
      { label: 'Location risk', value: 'Low', trend: 'Guarded' },
    ],
    checks: [
      { label: 'Tracker shield', detail: 'Known high-risk trackers are being blocked.', status: 'Protected' },
      { label: 'Data exposure', detail: 'Three broker listings are ready for opt-out workflow.', status: 'Warning' },
      { label: 'Location privacy', detail: 'Precise location is restricted for most apps.', status: 'Protected' },
    ],
    signals: ['Tracker reputation', 'Data broker listings', 'Location precision', 'Permission drift'],
    recommendations: ['Start opt-out for exposed broker listings.', 'Use approximate location unless precise location is necessary.'],
  },
  {
    id: 'file',
    title: 'File Protection',
    shortTitle: 'Files',
    category: 'Privacy',
    description: 'Protects sensitive files with classification, vaulting, leak checks, and suspicious-change alerts.',
    color: '#7c3aed',
    accent: 'rgba(124,58,237,0.16)',
    score: 90,
    incidents: 1,
    status: 'Protected',
    minPlan: 'premium',
    metrics: [
      { label: 'Sensitive files', value: '142', trend: 'Classified' },
      { label: 'Vaulted', value: '28', trend: 'Protected' },
      { label: 'Leak risk', value: 'Low', trend: 'Stable' },
    ],
    checks: [
      { label: 'Sensitive file AI', detail: 'Documents are classified locally before cloud analysis is requested.', status: 'Protected' },
      { label: 'Vault health', detail: 'Protected file vault is healthy.', status: 'Protected' },
      { label: 'Change monitor', detail: 'One unexpected rename pattern was reviewed.', status: 'Monitoring' },
    ],
    signals: ['Document type', 'Sensitive terms', 'Change bursts', 'Sharing status'],
    recommendations: ['Move tax and identity documents into the vault.', 'Avoid sharing sensitive screenshots in public chats.'],
  },
  {
    id: 'zero-day',
    title: 'Zero-Day Threat Detection',
    shortTitle: 'Zero-Day',
    category: 'AI Intelligence',
    description: 'Uses behavior, exploit-chain, and threat intelligence signals to flag never-before-seen attacks.',
    color: '#ff3b5c',
    accent: 'rgba(255,59,92,0.16)',
    score: 88,
    incidents: 1,
    status: 'Monitoring',
    minPlan: 'professional',
    metrics: [
      { label: 'Anomalies', value: '1', trend: 'Review' },
      { label: 'Model confidence', value: '92%', trend: 'Strong' },
      { label: 'Exploit chains', value: '0', trend: 'Blocked' },
    ],
    checks: [
      { label: 'Behavior model', detail: 'The model identifies unusual process, network, and file behavior.', status: 'Monitoring' },
      { label: 'Exploit-chain guard', detail: 'Suspicious multi-step activity is correlated across modules.', status: 'Protected' },
      { label: 'Rapid containment', detail: 'Recommended containment steps are generated automatically.', status: 'Protected' },
    ],
    signals: ['Anomaly clusters', 'Exploit chains', 'Memory behavior', 'Threat intel'],
    recommendations: ['Review the anomaly timeline.', 'Keep auto-containment enabled for critical assets.'],
  },
  {
    id: 'ai-attacks',
    title: 'AI Attack Detection',
    shortTitle: 'AI Attacks',
    category: 'AI Intelligence',
    description: 'Detects AI-assisted phishing, prompt injection attempts, deep social engineering, and synthetic lures.',
    color: '#00d4ff',
    accent: 'rgba(0,212,255,0.15)',
    score: 86,
    incidents: 2,
    status: 'Monitoring',
    minPlan: 'business',
    metrics: [
      { label: 'AI lures', value: '2', trend: 'Flagged' },
      { label: 'Prompt attacks', value: '0', trend: 'Clean' },
      { label: 'Synthetic risk', value: '17%', trend: 'Low' },
    ],
    checks: [
      { label: 'Synthetic content cues', detail: 'Detects AI-generated persuasion patterns and inconsistencies.', status: 'Monitoring' },
      { label: 'Prompt injection guard', detail: 'Submitted text and links are checked for instruction hijacking patterns.', status: 'Protected' },
      { label: 'AI lure analysis', detail: 'Scores urgency, personalization, and off-platform pressure.', status: 'Monitoring' },
    ],
    signals: ['Generated-language cues', 'Prompt patterns', 'Conversation structure', 'Off-platform pressure'],
    recommendations: ['Verify unusual highly personalized requests.', 'Never paste secret keys into untrusted AI tools.'],
  },
  {
    id: 'deepfake',
    title: 'Deepfake Detection',
    shortTitle: 'Deepfake',
    category: 'AI Intelligence',
    description: 'Reviews submitted media, profile images, and suspicious videos for manipulation and identity mismatch.',
    color: '#7c3aed',
    accent: 'rgba(124,58,237,0.18)',
    score: 79,
    incidents: 3,
    status: 'Warning',
    minPlan: 'professional',
    metrics: [
      { label: 'Media analyzed', value: '14', trend: '+5 week' },
      { label: 'High-risk media', value: '3', trend: 'Review' },
      { label: 'Confidence', value: '84%', trend: 'Median' },
    ],
    checks: [
      { label: 'Face consistency', detail: 'Looks for visual artifacts and inconsistent identity signals.', status: 'Monitoring' },
      { label: 'Voice risk', detail: 'Audio deepfake checks are available for submitted clips.', status: 'Monitoring' },
      { label: 'Profile mismatch', detail: 'Compares public image cues with provided profile context.', status: 'Warning' },
    ],
    signals: ['Image artifacts', 'Voice cues', 'Metadata mismatch', 'Profile age'],
    recommendations: ['Use a live verification call for high-risk relationships or payments.', 'Do not rely on a single image as proof of identity.'],
  },
  {
    id: 'threat-intel',
    title: 'Real-Time Threat Intelligence',
    shortTitle: 'Threat Intel',
    category: 'AI Intelligence',
    description: 'Correlates active campaigns, malicious infrastructure, breach data, and global risk signals.',
    color: '#0ff4c6',
    accent: 'rgba(15,244,198,0.14)',
    score: 94,
    incidents: 0,
    status: 'Protected',
    minPlan: 'business',
    metrics: [
      { label: 'Signals/day', value: '10M+', trend: 'Live' },
      { label: 'Campaigns', value: '8', trend: 'Tracked' },
      { label: 'Blocks', value: '2.8K', trend: 'Lifetime' },
    ],
    checks: [
      { label: 'Campaign feed', detail: 'Active phishing, malware, and fraud campaigns are correlated.', status: 'Protected' },
      { label: 'Infrastructure watch', detail: 'Command-and-control and malicious domains are tracked.', status: 'Protected' },
      { label: 'Local risk matching', detail: 'Your device and identity indicators are matched against active threats.', status: 'Monitoring' },
    ],
    signals: ['Campaign IOCs', 'Malicious IPs', 'Breach intelligence', 'Fraud infrastructure'],
    recommendations: ['Review threat reports weekly.', 'Enable business-wide alerts for executive impersonation campaigns.'],
  },
  {
    id: 'ddos-monitoring',
    title: 'DDoS Monitoring',
    shortTitle: 'DDoS',
    category: 'Network',
    description: 'Enterprise traffic baselining, volumetric anomaly alerts, and mitigation readiness for exposed services.',
    color: '#00d4ff',
    accent: 'rgba(0,212,255,0.14)',
    score: 91,
    incidents: 0,
    status: 'Monitoring',
    minPlan: 'enterprise',
    metrics: [
      { label: 'Traffic baseline', value: '99%', trend: 'Modeled' },
      { label: 'Edge regions', value: '12', trend: 'Watched' },
      { label: 'Mitigations', value: 'Ready', trend: 'Playbook' },
    ],
    checks: [
      { label: 'Traffic anomaly model', detail: 'Detects unusual packet, request, and regional traffic spikes.', status: 'Monitoring' },
      { label: 'Rate-limit posture', detail: 'Critical endpoints have mitigation rules prepared.', status: 'Protected' },
      { label: 'Provider escalation', detail: 'Runbooks include upstream provider contacts and response steps.', status: 'Protected' },
    ],
    signals: ['Traffic spikes', 'Request floods', 'Bot signatures', 'Edge telemetry'],
    recommendations: ['Run a quarterly DDoS tabletop exercise.', 'Keep emergency rate-limit rules reviewed.'],
  },
  {
    id: 'sql-injection',
    title: 'SQL Injection Detection',
    shortTitle: 'SQLi',
    category: 'AI Intelligence',
    description: 'Detects SQL injection probes, risky parameters, query anomalies, and unsafe data-access patterns.',
    color: '#f59e0b',
    accent: 'rgba(245,158,11,0.15)',
    score: 89,
    incidents: 1,
    status: 'Monitoring',
    minPlan: 'enterprise',
    metrics: [
      { label: 'Endpoints', value: '184', trend: 'Mapped' },
      { label: 'Payloads', value: '1', trend: 'Blocked' },
      { label: 'ORM health', value: '96%', trend: 'Strong' },
    ],
    checks: [
      { label: 'Injection payload watch', detail: 'Suspicious query strings and request bodies are scored.', status: 'Monitoring' },
      { label: 'Parameterized query review', detail: 'Data-access paths are checked for unsafe interpolation.', status: 'Protected' },
      { label: 'Database error leakage', detail: 'Verbose SQL errors are monitored as exposure signals.', status: 'Protected' },
    ],
    signals: ['SQL payloads', 'Query errors', 'Parameter anomalies', 'Endpoint exposure'],
    recommendations: ['Keep parameterized queries mandatory.', 'Add regression tests for risky search and filter endpoints.'],
  },
  {
    id: 'api-security',
    title: 'API Security Monitoring',
    shortTitle: 'API Security',
    category: 'Network',
    description: 'Monitors APIs for abuse, auth drift, schema changes, token misuse, and sensitive data exposure.',
    color: '#0ff4c6',
    accent: 'rgba(15,244,198,0.14)',
    score: 92,
    incidents: 0,
    status: 'Protected',
    minPlan: 'enterprise',
    metrics: [
      { label: 'APIs watched', value: '38', trend: 'Live' },
      { label: 'Auth drift', value: '0', trend: 'Clean' },
      { label: 'Risk calls', value: '4', trend: 'Reviewed' },
    ],
    checks: [
      { label: 'Token misuse', detail: 'Access tokens are checked for unusual scope and usage patterns.', status: 'Protected' },
      { label: 'Schema drift', detail: 'Unexpected request and response shapes create review tasks.', status: 'Monitoring' },
      { label: 'Sensitive data egress', detail: 'Responses are checked for accidental PII and secret exposure.', status: 'Protected' },
    ],
    signals: ['Auth scopes', 'Schema drift', 'Rate anomalies', 'Sensitive fields'],
    recommendations: ['Rotate API keys on schedule.', 'Require least-privilege scopes for service tokens.'],
  },
  {
    id: 'siem',
    title: 'SIEM Integrations',
    shortTitle: 'SIEM',
    category: 'AI Intelligence',
    description: 'Streams alerts, threat intelligence, investigations, and audit events into enterprise SIEM workflows.',
    color: '#7c3aed',
    accent: 'rgba(124,58,237,0.17)',
    score: 90,
    incidents: 0,
    status: 'Protected',
    minPlan: 'enterprise',
    metrics: [
      { label: 'Connectors', value: '6', trend: 'Ready' },
      { label: 'Events/day', value: '1.3M', trend: 'Streamed' },
      { label: 'Dropped events', value: '0', trend: 'Healthy' },
    ],
    checks: [
      { label: 'Connector health', detail: 'SIEM forwarders and webhooks are monitored for delivery health.', status: 'Protected' },
      { label: 'Alert normalization', detail: 'Events are mapped into consistent categories and severities.', status: 'Protected' },
      { label: 'Investigation export', detail: 'AI summaries can be exported into incident tickets.', status: 'Monitoring' },
    ],
    signals: ['Event delivery', 'Connector status', 'Severity mapping', 'Case exports'],
    recommendations: ['Test SIEM delivery weekly.', 'Map critical Deltex alerts to incident response queues.'],
  },
  {
    id: 'compliance',
    title: 'Compliance Tools',
    shortTitle: 'Compliance',
    category: 'Privacy',
    description: 'Business compliance posture, policy checks, audit evidence, and privacy control tracking.',
    color: '#f59e0b',
    accent: 'rgba(245,158,11,0.15)',
    score: 87,
    incidents: 2,
    status: 'Monitoring',
    minPlan: 'business',
    metrics: [
      { label: 'Policies', value: '24', trend: 'Tracked' },
      { label: 'Evidence', value: '91%', trend: 'Complete' },
      { label: 'Open gaps', value: '2', trend: 'Review' },
    ],
    checks: [
      { label: 'Policy coverage', detail: 'Security, privacy, and access policies are mapped to controls.', status: 'Monitoring' },
      { label: 'Audit evidence', detail: 'Reports, alerts, and configuration proofs are collected.', status: 'Protected' },
      { label: 'Access reviews', detail: 'User and team access reviews are scheduled.', status: 'Monitoring' },
    ],
    signals: ['Policy status', 'Control evidence', 'Access reviews', 'Audit gaps'],
    recommendations: ['Close the two evidence gaps.', 'Schedule monthly access review reminders.'],
  },
  {
    id: 'executive-reporting',
    title: 'Executive Reporting',
    shortTitle: 'Exec Reports',
    category: 'AI Intelligence',
    description: 'Board-ready security posture, risk trends, token usage, incidents, and executive summaries.',
    color: '#ff3b5c',
    accent: 'rgba(255,59,92,0.15)',
    score: 93,
    incidents: 0,
    status: 'Protected',
    minPlan: 'enterprise',
    metrics: [
      { label: 'Reports', value: '12', trend: 'Monthly' },
      { label: 'Risk trend', value: '-18%', trend: 'Improved' },
      { label: 'SLA health', value: '99%', trend: 'Met' },
    ],
    checks: [
      { label: 'Executive summary', detail: 'AI turns incidents, posture, and recommendations into clear summaries.', status: 'Protected' },
      { label: 'Risk trend analysis', detail: 'Tracks exposure, detection, response, and remediation movement.', status: 'Protected' },
      { label: 'Export workflow', detail: 'Reports are prepared for leadership, compliance, and security teams.', status: 'Monitoring' },
    ],
    signals: ['Posture trends', 'Incident summaries', 'Token usage', 'Business risk'],
    recommendations: ['Review executive report monthly.', 'Link high-risk findings to remediation owners.'],
  },
];

export const RECENT_THREATS = [
  { type: 'Phishing', source: 'email: secure-update@payrnents-login.com', severity: 'critical', time: '2m ago', blocked: true },
  { type: 'Family Safety', source: 'DM contact requested secrecy and gift cards', severity: 'high', time: '7m ago', blocked: true },
  { type: 'Website', source: 'storefront TLS certificate expires soon', severity: 'medium', time: '11m ago', blocked: false },
  { type: 'Firewall', source: 'blocked redirect to harmful checkout clone', severity: 'high', time: '13m ago', blocked: true },
  { type: 'Malware', source: 'download: free-vpn-pro.apk', severity: 'high', time: '15m ago', blocked: true },
  { type: 'Dark Web', source: 'email found in combo list', severity: 'medium', time: '3h ago', blocked: false },
  { type: 'Network', source: 'untrusted DNS redirect attempt', severity: 'low', time: '6h ago', blocked: true },
];

export const THREAT_TIMELINE = [
  { label: '00', threats: 2, blocked: 2 },
  { label: '04', threats: 5, blocked: 5 },
  { label: '08', threats: 18, blocked: 17 },
  { label: '12', threats: 34, blocked: 33 },
  { label: '16', threats: 28, blocked: 28 },
  { label: '20', threats: 12, blocked: 12 },
  { label: 'Now', threats: 7, blocked: 7 },
];

export const SCORE_HISTORY = [
  { label: 'Mon', value: 72 },
  { label: 'Tue', value: 76 },
  { label: 'Wed', value: 71 },
  { label: 'Thu', value: 84 },
  { label: 'Fri', value: 88 },
  { label: 'Sat', value: 91 },
  { label: 'Sun', value: 94 },
];

export const PAYMENT_METHODS = ['Apple Pay', 'Google Pay', 'PayPal', 'Visa', 'Mastercard', 'M-Pesa'];

export const INVOICES = [
  { date: 'Jun 1, 2026', amount: '$9.99', status: 'Paid' },
  { date: 'May 1, 2026', amount: '$9.99', status: 'Paid' },
  { date: 'Apr 1, 2026', amount: '$9.99', status: 'Paid' },
];

export const SECURITY_REPORTS: SecurityReport[] = [
  {
    id: 'weekly-security',
    title: 'Weekly Security Report',
    detail: 'Threats, posture, and AI recommendations for the current user.',
    category: 'Operations',
    status: 'Ready',
    kpis: ['Security score trend', 'Blocked threats', 'Critical alerts', 'Open recommendations'],
    actions: ['Review critical alerts', 'Run AI scan', 'Export summary'],
  },
  {
    id: 'frontend-implementation',
    title: 'Frontend Implementation Report',
    detail: 'Tracks the platform UI, subscription access, settings, dashboards, and Expo compatibility.',
    category: 'Implementation',
    status: 'Actionable',
    kpis: ['Component coverage', 'Plan gating', 'Theme support', 'Responsive screen fit'],
    actions: ['Keep six-plan subscription UI', 'Preserve dark/light/system themes', 'Monitor lint and TypeScript'],
  },
  {
    id: 'cyber-automation',
    title: 'Cyber Automation Protection Report',
    detail: 'Maps automation controls to scanning, anomaly detection, playbooks, rollback, and AI validation.',
    category: 'Research',
    status: 'Actionable',
    kpis: ['Asset coverage', 'MTTD/MTTC', 'MFA coverage', 'Restore test success'],
    actions: ['Prioritize visibility', 'Harden identity', 'Add response playbooks', 'Keep human approval for high-impact AI actions'],
  },
  {
    id: 'identity-exposure',
    title: 'Identity Exposure Report',
    detail: 'Dark web, credential leak, account takeover, and fraud-risk monitoring.',
    category: 'Operations',
    status: 'Monitoring',
    kpis: ['Leaks found', 'Passkey coverage', 'MFA coverage', 'Recovery events'],
    actions: ['Rotate exposed passwords', 'Enable passkeys', 'Review recovery methods'],
  },
  {
    id: 'social-scam',
    title: 'Social Media Protection Report',
    detail: 'Linked accounts, public profiles, suspicious pages, messages, screenshots, links, caller reputation, and safety scores.',
    category: 'Operations',
    status: 'Ready',
    kpis: ['Trust score', 'Fraud risk score', 'Impersonation risk', 'Malicious links'],
    actions: ['Analyze new profiles', 'Verify identity independently', 'Block suspicious contacts', 'Review fake business pages'],
  },
  {
    id: 'family-safety',
    title: 'Child & Family Safety Report',
    detail: 'Guardian-approved monitoring for grooming behavior, suspicious contacts, fake giveaways, youth scams, phishing, and harmful interactions.',
    category: 'Operations',
    status: 'Monitoring',
    kpis: ['Family profiles', 'Flagged contacts', 'Consent policies', 'Youth scam alerts'],
    actions: ['Review flagged conversations', 'Update guardian permissions', 'Block suspicious contacts', 'Schedule family safety scan'],
  },
  {
    id: 'website-protection',
    title: 'Website Protection Report',
    detail: 'Registered websites, SSL/TLS posture, domain reputation, malicious change monitoring, malware indicators, exposed credentials, and security baselines.',
    category: 'Operations',
    status: 'Actionable',
    kpis: ['Website risk score', 'Baseline drift', 'SSL/TLS issues', 'Reputation alerts'],
    actions: ['Register missing sites', 'Fix weak headers', 'Review domain risk', 'Schedule website posture scan'],
  },
  {
    id: 'personal-firewall',
    title: 'Personal Security Firewall Report',
    detail: 'Suspicious links, malicious domains, risky websites, phishing attempts, scam communications, fraudulent downloads, and network filtering actions.',
    category: 'Operations',
    status: 'Ready',
    kpis: ['Rules active', 'Blocked links', 'Filtered downloads', 'Policy recommendations'],
    actions: ['Review firewall rules', 'Enable high-risk link blocking', 'Tune trusted domains', 'Export firewall history'],
  },
];

export const SETUP_STEPS = [
  'Enable real-time threat scanning',
  'Turn on dark web and credential monitoring',
  'Protect browser, email, and SMS links',
  'Configure family safety permissions and child privacy controls',
  'Register websites, stores, portfolios, blogs, or apps for monitoring',
  'Enable the personal security firewall for links, domains, downloads, and scam communications',
  'Enable biometrics, passkeys, and multi-factor authentication',
  'Configure privacy-safe social media analysis',
];
